services:
  db:
    image: postgres:18.1-alpine
    container_name: db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - local-nestjs-boilerplate-data:/data/db

volumes:
  local-nestjs-boilerplate-data:
